#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUYENDUNGVIECLAM.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TUYENDUNGVIECLAM")]
	public partial class TUYENDUNGDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAdmin(Admin instance);
    partial void UpdateAdmin(Admin instance);
    partial void DeleteAdmin(Admin instance);
    partial void InsertApplication(Application instance);
    partial void UpdateApplication(Application instance);
    partial void DeleteApplication(Application instance);
    partial void InsertEmployer(Employer instance);
    partial void UpdateEmployer(Employer instance);
    partial void DeleteEmployer(Employer instance);
    partial void InsertJob(Job instance);
    partial void UpdateJob(Job instance);
    partial void DeleteJob(Job instance);
    partial void InsertJobseeker(Jobseeker instance);
    partial void UpdateJobseeker(Jobseeker instance);
    partial void DeleteJobseeker(Jobseeker instance);
    partial void InsertSaved(Saved instance);
    partial void UpdateSaved(Saved instance);
    partial void DeleteSaved(Saved instance);
    #endregion
		
		public TUYENDUNGDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TUYENDUNGVIECLAMConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TUYENDUNGDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TUYENDUNGDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TUYENDUNGDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TUYENDUNGDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Admin> Admins
		{
			get
			{
				return this.GetTable<Admin>();
			}
		}
		
		public System.Data.Linq.Table<Application> Applications
		{
			get
			{
				return this.GetTable<Application>();
			}
		}
		
		public System.Data.Linq.Table<Employer> Employers
		{
			get
			{
				return this.GetTable<Employer>();
			}
		}
		
		public System.Data.Linq.Table<Job> Jobs
		{
			get
			{
				return this.GetTable<Job>();
			}
		}
		
		public System.Data.Linq.Table<Jobseeker> Jobseekers
		{
			get
			{
				return this.GetTable<Jobseeker>();
			}
		}
		
		public System.Data.Linq.Table<Saved> Saveds
		{
			get
			{
				return this.GetTable<Saved>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Applied")]
		public ISingleResult<AppliedResult> Applied([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<AppliedResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.[Save]")]
		public ISingleResult<SaveResult> Save([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username);
			return ((ISingleResult<SaveResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListApplyMyJob")]
		public ISingleResult<ListApplyMyJobResult> ListApplyMyJob([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((ISingleResult<ListApplyMyJobResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Admin")]
	public partial class Admin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    #endregion
		
		public Admin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(50)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Application")]
	public partial class Application : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _job_id;
		
		private string _jobseekr_usernmae;
		
		private EntityRef<Job> _Job;
		
		private EntityRef<Jobseeker> _Jobseeker;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onjob_idChanging(System.Nullable<int> value);
    partial void Onjob_idChanged();
    partial void Onjobseekr_usernmaeChanging(string value);
    partial void Onjobseekr_usernmaeChanged();
    #endregion
		
		public Application()
		{
			this._Job = default(EntityRef<Job>);
			this._Jobseeker = default(EntityRef<Jobseeker>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int")]
		public System.Nullable<int> job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					if (this._Job.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobseekr_usernmae", DbType="VarChar(100)")]
		public string jobseekr_usernmae
		{
			get
			{
				return this._jobseekr_usernmae;
			}
			set
			{
				if ((this._jobseekr_usernmae != value))
				{
					if (this._Jobseeker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjobseekr_usernmaeChanging(value);
					this.SendPropertyChanging();
					this._jobseekr_usernmae = value;
					this.SendPropertyChanged("jobseekr_usernmae");
					this.Onjobseekr_usernmaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Job_Application", Storage="_Job", ThisKey="job_id", OtherKey="job_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Job Job
		{
			get
			{
				return this._Job.Entity;
			}
			set
			{
				Job previousValue = this._Job.Entity;
				if (((previousValue != value) 
							|| (this._Job.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Job.Entity = null;
						previousValue.Applications.Remove(this);
					}
					this._Job.Entity = value;
					if ((value != null))
					{
						value.Applications.Add(this);
						this._job_id = value.job_id;
					}
					else
					{
						this._job_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Job");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jobseeker_Application", Storage="_Jobseeker", ThisKey="jobseekr_usernmae", OtherKey="username", IsForeignKey=true, DeleteRule="CASCADE")]
		public Jobseeker Jobseeker
		{
			get
			{
				return this._Jobseeker.Entity;
			}
			set
			{
				Jobseeker previousValue = this._Jobseeker.Entity;
				if (((previousValue != value) 
							|| (this._Jobseeker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jobseeker.Entity = null;
						previousValue.Applications.Remove(this);
					}
					this._Jobseeker.Entity = value;
					if ((value != null))
					{
						value.Applications.Add(this);
						this._jobseekr_usernmae = value.username;
					}
					else
					{
						this._jobseekr_usernmae = default(string);
					}
					this.SendPropertyChanged("Jobseeker");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employer")]
	public partial class Employer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _address;
		
		private string _tel;
		
		private string _email;
		
		private string _password;
		
		private string _aboutus;
		
		private string _webiste;
		
		private string _contact_phone;
		
		private string _location;
		
		private string _contact_person;
		
		private string _amount_employee;
		
		private string _username;
		
		private EntitySet<Job> _Jobs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnaboutusChanging(string value);
    partial void OnaboutusChanged();
    partial void OnwebisteChanging(string value);
    partial void OnwebisteChanged();
    partial void Oncontact_phoneChanging(string value);
    partial void Oncontact_phoneChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Oncontact_personChanging(string value);
    partial void Oncontact_personChanged();
    partial void Onamount_employeeChanging(string value);
    partial void Onamount_employeeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public Employer()
		{
			this._Jobs = new EntitySet<Job>(new Action<Job>(this.attach_Jobs), new Action<Job>(this.detach_Jobs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(200)")]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(200)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="VarChar(11)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aboutus", DbType="NVarChar(MAX)")]
		public string aboutus
		{
			get
			{
				return this._aboutus;
			}
			set
			{
				if ((this._aboutus != value))
				{
					this.OnaboutusChanging(value);
					this.SendPropertyChanging();
					this._aboutus = value;
					this.SendPropertyChanged("aboutus");
					this.OnaboutusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_webiste", DbType="VarChar(300)")]
		public string webiste
		{
			get
			{
				return this._webiste;
			}
			set
			{
				if ((this._webiste != value))
				{
					this.OnwebisteChanging(value);
					this.SendPropertyChanging();
					this._webiste = value;
					this.SendPropertyChanged("webiste");
					this.OnwebisteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_phone", DbType="VarChar(15)")]
		public string contact_phone
		{
			get
			{
				return this._contact_phone;
			}
			set
			{
				if ((this._contact_phone != value))
				{
					this.Oncontact_phoneChanging(value);
					this.SendPropertyChanging();
					this._contact_phone = value;
					this.SendPropertyChanged("contact_phone");
					this.Oncontact_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(200)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contact_person", DbType="NVarChar(100)")]
		public string contact_person
		{
			get
			{
				return this._contact_person;
			}
			set
			{
				if ((this._contact_person != value))
				{
					this.Oncontact_personChanging(value);
					this.SendPropertyChanging();
					this._contact_person = value;
					this.SendPropertyChanged("contact_person");
					this.Oncontact_personChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_amount_employee", DbType="NVarChar(100)")]
		public string amount_employee
		{
			get
			{
				return this._amount_employee;
			}
			set
			{
				if ((this._amount_employee != value))
				{
					this.Onamount_employeeChanging(value);
					this.SendPropertyChanging();
					this._amount_employee = value;
					this.SendPropertyChanged("amount_employee");
					this.Onamount_employeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employer_Job", Storage="_Jobs", ThisKey="username", OtherKey="employer_usename")]
		public EntitySet<Job> Jobs
		{
			get
			{
				return this._Jobs;
			}
			set
			{
				this._Jobs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Jobs(Job entity)
		{
			this.SendPropertyChanging();
			entity.Employer = this;
		}
		
		private void detach_Jobs(Job entity)
		{
			this.SendPropertyChanging();
			entity.Employer = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Job")]
	public partial class Job : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _job_id;
		
		private string _job_title;
		
		private string _job_description;
		
		private string _job_type;
		
		private string _job_salar;
		
		private string _job_experience;
		
		private string _job_location;
		
		private System.Nullable<int> _job_state;
		
		private string _job_address;
		
		private string _job_category;
		
		private System.Nullable<System.DateTime> _job_starttime;
		
		private System.Nullable<System.DateTime> _job_postdate;
		
		private string _extraskill;
		
		private string _require_skill;
		
		private string _job_benefit;
		
		private string _employer_usename;
		
		private EntitySet<Application> _Applications;
		
		private EntitySet<Saved> _Saveds;
		
		private EntityRef<Employer> _Employer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onjob_idChanging(int value);
    partial void Onjob_idChanged();
    partial void Onjob_titleChanging(string value);
    partial void Onjob_titleChanged();
    partial void Onjob_descriptionChanging(string value);
    partial void Onjob_descriptionChanged();
    partial void Onjob_typeChanging(string value);
    partial void Onjob_typeChanged();
    partial void Onjob_salarChanging(string value);
    partial void Onjob_salarChanged();
    partial void Onjob_experienceChanging(string value);
    partial void Onjob_experienceChanged();
    partial void Onjob_locationChanging(string value);
    partial void Onjob_locationChanged();
    partial void Onjob_stateChanging(System.Nullable<int> value);
    partial void Onjob_stateChanged();
    partial void Onjob_addressChanging(string value);
    partial void Onjob_addressChanged();
    partial void Onjob_categoryChanging(string value);
    partial void Onjob_categoryChanged();
    partial void Onjob_starttimeChanging(System.Nullable<System.DateTime> value);
    partial void Onjob_starttimeChanged();
    partial void Onjob_postdateChanging(System.Nullable<System.DateTime> value);
    partial void Onjob_postdateChanged();
    partial void OnextraskillChanging(string value);
    partial void OnextraskillChanged();
    partial void Onrequire_skillChanging(string value);
    partial void Onrequire_skillChanged();
    partial void Onjob_benefitChanging(string value);
    partial void Onjob_benefitChanged();
    partial void Onemployer_usenameChanging(string value);
    partial void Onemployer_usenameChanged();
    #endregion
		
		public Job()
		{
			this._Applications = new EntitySet<Application>(new Action<Application>(this.attach_Applications), new Action<Application>(this.detach_Applications));
			this._Saveds = new EntitySet<Saved>(new Action<Saved>(this.attach_Saveds), new Action<Saved>(this.detach_Saveds));
			this._Employer = default(EntityRef<Employer>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string job_title
		{
			get
			{
				return this._job_title;
			}
			set
			{
				if ((this._job_title != value))
				{
					this.Onjob_titleChanging(value);
					this.SendPropertyChanging();
					this._job_title = value;
					this.SendPropertyChanged("job_title");
					this.Onjob_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_description", DbType="NVarChar(MAX)")]
		public string job_description
		{
			get
			{
				return this._job_description;
			}
			set
			{
				if ((this._job_description != value))
				{
					this.Onjob_descriptionChanging(value);
					this.SendPropertyChanging();
					this._job_description = value;
					this.SendPropertyChanged("job_description");
					this.Onjob_descriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="VarChar(100)")]
		public string job_type
		{
			get
			{
				return this._job_type;
			}
			set
			{
				if ((this._job_type != value))
				{
					this.Onjob_typeChanging(value);
					this.SendPropertyChanging();
					this._job_type = value;
					this.SendPropertyChanged("job_type");
					this.Onjob_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_salar", DbType="VarChar(100)")]
		public string job_salar
		{
			get
			{
				return this._job_salar;
			}
			set
			{
				if ((this._job_salar != value))
				{
					this.Onjob_salarChanging(value);
					this.SendPropertyChanging();
					this._job_salar = value;
					this.SendPropertyChanged("job_salar");
					this.Onjob_salarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_experience", DbType="NVarChar(100)")]
		public string job_experience
		{
			get
			{
				return this._job_experience;
			}
			set
			{
				if ((this._job_experience != value))
				{
					this.Onjob_experienceChanging(value);
					this.SendPropertyChanging();
					this._job_experience = value;
					this.SendPropertyChanged("job_experience");
					this.Onjob_experienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_location", DbType="NVarChar(300)")]
		public string job_location
		{
			get
			{
				return this._job_location;
			}
			set
			{
				if ((this._job_location != value))
				{
					this.Onjob_locationChanging(value);
					this.SendPropertyChanging();
					this._job_location = value;
					this.SendPropertyChanged("job_location");
					this.Onjob_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_state", DbType="Int")]
		public System.Nullable<int> job_state
		{
			get
			{
				return this._job_state;
			}
			set
			{
				if ((this._job_state != value))
				{
					this.Onjob_stateChanging(value);
					this.SendPropertyChanging();
					this._job_state = value;
					this.SendPropertyChanged("job_state");
					this.Onjob_stateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_address", DbType="NVarChar(300)")]
		public string job_address
		{
			get
			{
				return this._job_address;
			}
			set
			{
				if ((this._job_address != value))
				{
					this.Onjob_addressChanging(value);
					this.SendPropertyChanging();
					this._job_address = value;
					this.SendPropertyChanged("job_address");
					this.Onjob_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_category", DbType="NVarChar(200)")]
		public string job_category
		{
			get
			{
				return this._job_category;
			}
			set
			{
				if ((this._job_category != value))
				{
					this.Onjob_categoryChanging(value);
					this.SendPropertyChanging();
					this._job_category = value;
					this.SendPropertyChanged("job_category");
					this.Onjob_categoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_starttime", DbType="Date")]
		public System.Nullable<System.DateTime> job_starttime
		{
			get
			{
				return this._job_starttime;
			}
			set
			{
				if ((this._job_starttime != value))
				{
					this.Onjob_starttimeChanging(value);
					this.SendPropertyChanging();
					this._job_starttime = value;
					this.SendPropertyChanged("job_starttime");
					this.Onjob_starttimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_postdate", DbType="Date")]
		public System.Nullable<System.DateTime> job_postdate
		{
			get
			{
				return this._job_postdate;
			}
			set
			{
				if ((this._job_postdate != value))
				{
					this.Onjob_postdateChanging(value);
					this.SendPropertyChanging();
					this._job_postdate = value;
					this.SendPropertyChanged("job_postdate");
					this.Onjob_postdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraskill", DbType="NVarChar(100)")]
		public string extraskill
		{
			get
			{
				return this._extraskill;
			}
			set
			{
				if ((this._extraskill != value))
				{
					this.OnextraskillChanging(value);
					this.SendPropertyChanging();
					this._extraskill = value;
					this.SendPropertyChanged("extraskill");
					this.OnextraskillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_require_skill", DbType="NVarChar(MAX)")]
		public string require_skill
		{
			get
			{
				return this._require_skill;
			}
			set
			{
				if ((this._require_skill != value))
				{
					this.Onrequire_skillChanging(value);
					this.SendPropertyChanging();
					this._require_skill = value;
					this.SendPropertyChanged("require_skill");
					this.Onrequire_skillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_benefit", DbType="NVarChar(300)")]
		public string job_benefit
		{
			get
			{
				return this._job_benefit;
			}
			set
			{
				if ((this._job_benefit != value))
				{
					this.Onjob_benefitChanging(value);
					this.SendPropertyChanging();
					this._job_benefit = value;
					this.SendPropertyChanged("job_benefit");
					this.Onjob_benefitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer_usename", DbType="VarChar(100)")]
		public string employer_usename
		{
			get
			{
				return this._employer_usename;
			}
			set
			{
				if ((this._employer_usename != value))
				{
					if (this._Employer.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onemployer_usenameChanging(value);
					this.SendPropertyChanging();
					this._employer_usename = value;
					this.SendPropertyChanged("employer_usename");
					this.Onemployer_usenameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Job_Application", Storage="_Applications", ThisKey="job_id", OtherKey="job_id")]
		public EntitySet<Application> Applications
		{
			get
			{
				return this._Applications;
			}
			set
			{
				this._Applications.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Job_Saved", Storage="_Saveds", ThisKey="job_id", OtherKey="job_id")]
		public EntitySet<Saved> Saveds
		{
			get
			{
				return this._Saveds;
			}
			set
			{
				this._Saveds.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Employer_Job", Storage="_Employer", ThisKey="employer_usename", OtherKey="username", IsForeignKey=true, DeleteRule="CASCADE")]
		public Employer Employer
		{
			get
			{
				return this._Employer.Entity;
			}
			set
			{
				Employer previousValue = this._Employer.Entity;
				if (((previousValue != value) 
							|| (this._Employer.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Employer.Entity = null;
						previousValue.Jobs.Remove(this);
					}
					this._Employer.Entity = value;
					if ((value != null))
					{
						value.Jobs.Add(this);
						this._employer_usename = value.username;
					}
					else
					{
						this._employer_usename = default(string);
					}
					this.SendPropertyChanged("Employer");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.Job = this;
		}
		
		private void detach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.Job = null;
		}
		
		private void attach_Saveds(Saved entity)
		{
			this.SendPropertyChanging();
			entity.Job = this;
		}
		
		private void detach_Saveds(Saved entity)
		{
			this.SendPropertyChanging();
			entity.Job = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Jobseeker")]
	public partial class Jobseeker : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _name;
		
		private string _phone;
		
		private string _address;
		
		private string _experience;
		
		private string _skill;
		
		private string _aboutme;
		
		private string _current_role;
		
		private string _password;
		
		private string _gender;
		
		private string _extraskill;
		
		private string _email;
		
		private string _place;
		
		private string _educational;
		
		private string _achivement;
		
		private string _career;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _username;
		
		private EntitySet<Application> _Applications;
		
		private EntitySet<Saved> _Saveds;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnnameChanging(string value);
    partial void OnnameChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnexperienceChanging(string value);
    partial void OnexperienceChanged();
    partial void OnskillChanging(string value);
    partial void OnskillChanged();
    partial void OnaboutmeChanging(string value);
    partial void OnaboutmeChanged();
    partial void Oncurrent_roleChanging(string value);
    partial void Oncurrent_roleChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OngenderChanging(string value);
    partial void OngenderChanged();
    partial void OnextraskillChanging(string value);
    partial void OnextraskillChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnplaceChanging(string value);
    partial void OnplaceChanged();
    partial void OneducationalChanging(string value);
    partial void OneducationalChanged();
    partial void OnachivementChanging(string value);
    partial void OnachivementChanged();
    partial void OncareerChanging(string value);
    partial void OncareerChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    #endregion
		
		public Jobseeker()
		{
			this._Applications = new EntitySet<Application>(new Action<Application>(this.attach_Applications), new Action<Application>(this.detach_Applications));
			this._Saveds = new EntitySet<Saved>(new Action<Saved>(this.attach_Saveds), new Action<Saved>(this.detach_Saveds));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this.OnnameChanging(value);
					this.SendPropertyChanging();
					this._name = value;
					this.SendPropertyChanged("name");
					this.OnnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(200)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experience", DbType="NVarChar(MAX)")]
		public string experience
		{
			get
			{
				return this._experience;
			}
			set
			{
				if ((this._experience != value))
				{
					this.OnexperienceChanging(value);
					this.SendPropertyChanging();
					this._experience = value;
					this.SendPropertyChanged("experience");
					this.OnexperienceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skill", DbType="NVarChar(MAX)")]
		public string skill
		{
			get
			{
				return this._skill;
			}
			set
			{
				if ((this._skill != value))
				{
					this.OnskillChanging(value);
					this.SendPropertyChanging();
					this._skill = value;
					this.SendPropertyChanged("skill");
					this.OnskillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aboutme", DbType="NVarChar(MAX)")]
		public string aboutme
		{
			get
			{
				return this._aboutme;
			}
			set
			{
				if ((this._aboutme != value))
				{
					this.OnaboutmeChanging(value);
					this.SendPropertyChanging();
					this._aboutme = value;
					this.SendPropertyChanged("aboutme");
					this.OnaboutmeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_role", DbType="NVarChar(100)")]
		public string current_role
		{
			get
			{
				return this._current_role;
			}
			set
			{
				if ((this._current_role != value))
				{
					this.Oncurrent_roleChanging(value);
					this.SendPropertyChanging();
					this._current_role = value;
					this.SendPropertyChanged("current_role");
					this.Oncurrent_roleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this.OngenderChanging(value);
					this.SendPropertyChanging();
					this._gender = value;
					this.SendPropertyChanged("gender");
					this.OngenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraskill", DbType="NVarChar(500)")]
		public string extraskill
		{
			get
			{
				return this._extraskill;
			}
			set
			{
				if ((this._extraskill != value))
				{
					this.OnextraskillChanging(value);
					this.SendPropertyChanging();
					this._extraskill = value;
					this.SendPropertyChanged("extraskill");
					this.OnextraskillChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place", DbType="NVarChar(100)")]
		public string place
		{
			get
			{
				return this._place;
			}
			set
			{
				if ((this._place != value))
				{
					this.OnplaceChanging(value);
					this.SendPropertyChanging();
					this._place = value;
					this.SendPropertyChanged("place");
					this.OnplaceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_educational", DbType="NVarChar(100)")]
		public string educational
		{
			get
			{
				return this._educational;
			}
			set
			{
				if ((this._educational != value))
				{
					this.OneducationalChanging(value);
					this.SendPropertyChanging();
					this._educational = value;
					this.SendPropertyChanged("educational");
					this.OneducationalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achivement", DbType="NVarChar(MAX)")]
		public string achivement
		{
			get
			{
				return this._achivement;
			}
			set
			{
				if ((this._achivement != value))
				{
					this.OnachivementChanging(value);
					this.SendPropertyChanging();
					this._achivement = value;
					this.SendPropertyChanged("achivement");
					this.OnachivementChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_career", DbType="NVarChar(100)")]
		public string career
		{
			get
			{
				return this._career;
			}
			set
			{
				if ((this._career != value))
				{
					this.OncareerChanging(value);
					this.SendPropertyChanging();
					this._career = value;
					this.SendPropertyChanged("career");
					this.OncareerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jobseeker_Application", Storage="_Applications", ThisKey="username", OtherKey="jobseekr_usernmae")]
		public EntitySet<Application> Applications
		{
			get
			{
				return this._Applications;
			}
			set
			{
				this._Applications.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jobseeker_Saved", Storage="_Saveds", ThisKey="username", OtherKey="jobseekr_usernmae")]
		public EntitySet<Saved> Saveds
		{
			get
			{
				return this._Saveds;
			}
			set
			{
				this._Saveds.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.Jobseeker = this;
		}
		
		private void detach_Applications(Application entity)
		{
			this.SendPropertyChanging();
			entity.Jobseeker = null;
		}
		
		private void attach_Saveds(Saved entity)
		{
			this.SendPropertyChanging();
			entity.Jobseeker = this;
		}
		
		private void detach_Saveds(Saved entity)
		{
			this.SendPropertyChanging();
			entity.Jobseeker = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Saved")]
	public partial class Saved : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<int> _job_id;
		
		private string _jobseekr_usernmae;
		
		private EntityRef<Job> _Job;
		
		private EntityRef<Jobseeker> _Jobseeker;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onjob_idChanging(System.Nullable<int> value);
    partial void Onjob_idChanged();
    partial void Onjobseekr_usernmaeChanging(string value);
    partial void Onjobseekr_usernmaeChanged();
    #endregion
		
		public Saved()
		{
			this._Job = default(EntityRef<Job>);
			this._Jobseeker = default(EntityRef<Jobseeker>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int")]
		public System.Nullable<int> job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					if (this._Job.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjob_idChanging(value);
					this.SendPropertyChanging();
					this._job_id = value;
					this.SendPropertyChanged("job_id");
					this.Onjob_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobseekr_usernmae", DbType="VarChar(100)")]
		public string jobseekr_usernmae
		{
			get
			{
				return this._jobseekr_usernmae;
			}
			set
			{
				if ((this._jobseekr_usernmae != value))
				{
					if (this._Jobseeker.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onjobseekr_usernmaeChanging(value);
					this.SendPropertyChanging();
					this._jobseekr_usernmae = value;
					this.SendPropertyChanged("jobseekr_usernmae");
					this.Onjobseekr_usernmaeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Job_Saved", Storage="_Job", ThisKey="job_id", OtherKey="job_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Job Job
		{
			get
			{
				return this._Job.Entity;
			}
			set
			{
				Job previousValue = this._Job.Entity;
				if (((previousValue != value) 
							|| (this._Job.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Job.Entity = null;
						previousValue.Saveds.Remove(this);
					}
					this._Job.Entity = value;
					if ((value != null))
					{
						value.Saveds.Add(this);
						this._job_id = value.job_id;
					}
					else
					{
						this._job_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("Job");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Jobseeker_Saved", Storage="_Jobseeker", ThisKey="jobseekr_usernmae", OtherKey="username", IsForeignKey=true, DeleteRule="CASCADE")]
		public Jobseeker Jobseeker
		{
			get
			{
				return this._Jobseeker.Entity;
			}
			set
			{
				Jobseeker previousValue = this._Jobseeker.Entity;
				if (((previousValue != value) 
							|| (this._Jobseeker.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Jobseeker.Entity = null;
						previousValue.Saveds.Remove(this);
					}
					this._Jobseeker.Entity = value;
					if ((value != null))
					{
						value.Saveds.Add(this);
						this._jobseekr_usernmae = value.username;
					}
					else
					{
						this._jobseekr_usernmae = default(string);
					}
					this.SendPropertyChanged("Jobseeker");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class AppliedResult
	{
		
		private int _job_id;
		
		private string _job_title;
		
		private string _job_description;
		
		private string _job_type;
		
		private string _job_salar;
		
		private string _job_experience;
		
		private string _job_location;
		
		private System.Nullable<int> _job_state;
		
		private string _job_address;
		
		private string _job_category;
		
		private System.Nullable<System.DateTime> _job_starttime;
		
		private System.Nullable<System.DateTime> _job_postdate;
		
		private string _extraskill;
		
		private string _require_skill;
		
		private string _job_benefit;
		
		private string _employer_usename;
		
		public AppliedResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int NOT NULL")]
		public int job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					this._job_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string job_title
		{
			get
			{
				return this._job_title;
			}
			set
			{
				if ((this._job_title != value))
				{
					this._job_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_description", DbType="NVarChar(MAX)")]
		public string job_description
		{
			get
			{
				return this._job_description;
			}
			set
			{
				if ((this._job_description != value))
				{
					this._job_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="VarChar(100)")]
		public string job_type
		{
			get
			{
				return this._job_type;
			}
			set
			{
				if ((this._job_type != value))
				{
					this._job_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_salar", DbType="VarChar(100)")]
		public string job_salar
		{
			get
			{
				return this._job_salar;
			}
			set
			{
				if ((this._job_salar != value))
				{
					this._job_salar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_experience", DbType="NVarChar(100)")]
		public string job_experience
		{
			get
			{
				return this._job_experience;
			}
			set
			{
				if ((this._job_experience != value))
				{
					this._job_experience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_location", DbType="NVarChar(300)")]
		public string job_location
		{
			get
			{
				return this._job_location;
			}
			set
			{
				if ((this._job_location != value))
				{
					this._job_location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_state", DbType="Int")]
		public System.Nullable<int> job_state
		{
			get
			{
				return this._job_state;
			}
			set
			{
				if ((this._job_state != value))
				{
					this._job_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_address", DbType="NVarChar(300)")]
		public string job_address
		{
			get
			{
				return this._job_address;
			}
			set
			{
				if ((this._job_address != value))
				{
					this._job_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_category", DbType="NVarChar(200)")]
		public string job_category
		{
			get
			{
				return this._job_category;
			}
			set
			{
				if ((this._job_category != value))
				{
					this._job_category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_starttime", DbType="Date")]
		public System.Nullable<System.DateTime> job_starttime
		{
			get
			{
				return this._job_starttime;
			}
			set
			{
				if ((this._job_starttime != value))
				{
					this._job_starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_postdate", DbType="Date")]
		public System.Nullable<System.DateTime> job_postdate
		{
			get
			{
				return this._job_postdate;
			}
			set
			{
				if ((this._job_postdate != value))
				{
					this._job_postdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraskill", DbType="NVarChar(100)")]
		public string extraskill
		{
			get
			{
				return this._extraskill;
			}
			set
			{
				if ((this._extraskill != value))
				{
					this._extraskill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_require_skill", DbType="NVarChar(100)")]
		public string require_skill
		{
			get
			{
				return this._require_skill;
			}
			set
			{
				if ((this._require_skill != value))
				{
					this._require_skill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_benefit", DbType="NVarChar(300)")]
		public string job_benefit
		{
			get
			{
				return this._job_benefit;
			}
			set
			{
				if ((this._job_benefit != value))
				{
					this._job_benefit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer_usename", DbType="VarChar(100)")]
		public string employer_usename
		{
			get
			{
				return this._employer_usename;
			}
			set
			{
				if ((this._employer_usename != value))
				{
					this._employer_usename = value;
				}
			}
		}
	}
	
	public partial class SaveResult
	{
		
		private int _job_id;
		
		private string _job_title;
		
		private string _job_description;
		
		private string _job_type;
		
		private string _job_salar;
		
		private string _job_experience;
		
		private string _job_location;
		
		private System.Nullable<int> _job_state;
		
		private string _job_address;
		
		private string _job_category;
		
		private System.Nullable<System.DateTime> _job_starttime;
		
		private System.Nullable<System.DateTime> _job_postdate;
		
		private string _extraskill;
		
		private string _require_skill;
		
		private string _job_benefit;
		
		private string _employer_usename;
		
		public SaveResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_id", DbType="Int NOT NULL")]
		public int job_id
		{
			get
			{
				return this._job_id;
			}
			set
			{
				if ((this._job_id != value))
				{
					this._job_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_title", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string job_title
		{
			get
			{
				return this._job_title;
			}
			set
			{
				if ((this._job_title != value))
				{
					this._job_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_description", DbType="NVarChar(MAX)")]
		public string job_description
		{
			get
			{
				return this._job_description;
			}
			set
			{
				if ((this._job_description != value))
				{
					this._job_description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_type", DbType="VarChar(100)")]
		public string job_type
		{
			get
			{
				return this._job_type;
			}
			set
			{
				if ((this._job_type != value))
				{
					this._job_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_salar", DbType="VarChar(100)")]
		public string job_salar
		{
			get
			{
				return this._job_salar;
			}
			set
			{
				if ((this._job_salar != value))
				{
					this._job_salar = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_experience", DbType="NVarChar(100)")]
		public string job_experience
		{
			get
			{
				return this._job_experience;
			}
			set
			{
				if ((this._job_experience != value))
				{
					this._job_experience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_location", DbType="NVarChar(300)")]
		public string job_location
		{
			get
			{
				return this._job_location;
			}
			set
			{
				if ((this._job_location != value))
				{
					this._job_location = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_state", DbType="Int")]
		public System.Nullable<int> job_state
		{
			get
			{
				return this._job_state;
			}
			set
			{
				if ((this._job_state != value))
				{
					this._job_state = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_address", DbType="NVarChar(300)")]
		public string job_address
		{
			get
			{
				return this._job_address;
			}
			set
			{
				if ((this._job_address != value))
				{
					this._job_address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_category", DbType="NVarChar(200)")]
		public string job_category
		{
			get
			{
				return this._job_category;
			}
			set
			{
				if ((this._job_category != value))
				{
					this._job_category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_starttime", DbType="Date")]
		public System.Nullable<System.DateTime> job_starttime
		{
			get
			{
				return this._job_starttime;
			}
			set
			{
				if ((this._job_starttime != value))
				{
					this._job_starttime = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_postdate", DbType="Date")]
		public System.Nullable<System.DateTime> job_postdate
		{
			get
			{
				return this._job_postdate;
			}
			set
			{
				if ((this._job_postdate != value))
				{
					this._job_postdate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraskill", DbType="NVarChar(100)")]
		public string extraskill
		{
			get
			{
				return this._extraskill;
			}
			set
			{
				if ((this._extraskill != value))
				{
					this._extraskill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_require_skill", DbType="NVarChar(100)")]
		public string require_skill
		{
			get
			{
				return this._require_skill;
			}
			set
			{
				if ((this._require_skill != value))
				{
					this._require_skill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_job_benefit", DbType="NVarChar(300)")]
		public string job_benefit
		{
			get
			{
				return this._job_benefit;
			}
			set
			{
				if ((this._job_benefit != value))
				{
					this._job_benefit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employer_usename", DbType="VarChar(100)")]
		public string employer_usename
		{
			get
			{
				return this._employer_usename;
			}
			set
			{
				if ((this._employer_usename != value))
				{
					this._employer_usename = value;
				}
			}
		}
	}
	
	public partial class ListApplyMyJobResult
	{
		
		private string _name;
		
		private string _phone;
		
		private string _address;
		
		private string _experience;
		
		private string _skill;
		
		private string _aboutme;
		
		private string _current_role;
		
		private string _password;
		
		private string _gender;
		
		private string _extraskill;
		
		private string _email;
		
		private string _place;
		
		private string _educational;
		
		private string _achivement;
		
		private string _career;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _username;
		
		public ListApplyMyJobResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				if ((this._name != value))
				{
					this._name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20)")]
		public string phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this._phone = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(200)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this._address = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experience", DbType="NVarChar(MAX)")]
		public string experience
		{
			get
			{
				return this._experience;
			}
			set
			{
				if ((this._experience != value))
				{
					this._experience = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skill", DbType="NVarChar(MAX)")]
		public string skill
		{
			get
			{
				return this._skill;
			}
			set
			{
				if ((this._skill != value))
				{
					this._skill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aboutme", DbType="NVarChar(MAX)")]
		public string aboutme
		{
			get
			{
				return this._aboutme;
			}
			set
			{
				if ((this._aboutme != value))
				{
					this._aboutme = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_current_role", DbType="NVarChar(100)")]
		public string current_role
		{
			get
			{
				return this._current_role;
			}
			set
			{
				if ((this._current_role != value))
				{
					this._current_role = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(100)")]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this._password = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gender", DbType="NVarChar(10)")]
		public string gender
		{
			get
			{
				return this._gender;
			}
			set
			{
				if ((this._gender != value))
				{
					this._gender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_extraskill", DbType="NVarChar(500)")]
		public string extraskill
		{
			get
			{
				return this._extraskill;
			}
			set
			{
				if ((this._extraskill != value))
				{
					this._extraskill = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this._email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_place", DbType="NVarChar(100)")]
		public string place
		{
			get
			{
				return this._place;
			}
			set
			{
				if ((this._place != value))
				{
					this._place = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_educational", DbType="NVarChar(100)")]
		public string educational
		{
			get
			{
				return this._educational;
			}
			set
			{
				if ((this._educational != value))
				{
					this._educational = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_achivement", DbType="NVarChar(MAX)")]
		public string achivement
		{
			get
			{
				return this._achivement;
			}
			set
			{
				if ((this._achivement != value))
				{
					this._achivement = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_career", DbType="NVarChar(100)")]
		public string career
		{
			get
			{
				return this._career;
			}
			set
			{
				if ((this._career != value))
				{
					this._career = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="Date")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this._birthday = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this._username = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
